syntax = "proto3";
package stable;

message GetPriceRequest {}
message GetPriceResponse {
  double price = 1;
}

message StableChannelInfo {
  string channel_id = 1;
  string counterparty = 2;
  double expected_usd = 3;
  uint64 expected_msats = 4;
  double latest_price = 5;
  string note = 6;
  bool is_stable_receiver = 7;
}

message ListStableChannelsRequest {}
message ListStableChannelsResponse {
  repeated StableChannelInfo channels = 1;
}

message EditStableChannelRequest {
  string channel_id = 1;
  optional double expected_usd = 2;
  optional string note = 3;
}
message EditStableChannelResponse {
  bool ok = 1;
  string status = 2;
}
