[package]
name = "ldk-server-client"
version = "0.1.0"
authors = ["benthecarman <benthecarman@live.com>", "Elias Rohrer <dev@tnull.de>"]
homepage = "https://lightningdevkit.org/"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.85"
description = "An async Rust client library for communicating with LDK Server."
repository = "https://github.com/lightningdevkit/ldk-server/"
documentation = "https://docs.rs/ldk-server-client"
readme = "README.md"
keywords = ["bitcoin", "lightning", "ldk", "server"]
categories = ["cryptography::cryptocurrencies"]

[features]
default = []
serde = ["dep:serde", "dep:toml", "ldk-server-grpc/serde"]

[dependencies]
ldk-server-grpc = { path = "../ldk-server-grpc" }
ldk-server-macaroons = { path = "../ldk-server-macaroons" }
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls"] }
prost = { version = "0.11.6", default-features = false, features = ["std", "prost-derive"] }
hyper = { version = "0.14", default-features = false, features = ["client", "http2", "runtime", "tcp"] }
hyper-rustls = { version = "0.24", default-features = false, features = ["http2", "tls12", "tokio-runtime"] }
rustls = "0.21"
rustls-pemfile = "1"
serde = { version = "1.0", features = ["derive"], optional = true }
toml = { version = "0.8", default-features = false, features = ["parse"], optional = true }

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt"] }
