# ldk-server-config.toml

# Lightning node settings
[node]
network = "signet"                            # Bitcoin network to use (mutinynet)
alias = "ldk-regtest"                         # REQUIRED for announcement (<=32 bytes, printable)
listening_addresses = ["127.0.0.1:3001"]      # Lightning node listening addresses
announcement_addresses = ["127.0.0.1:3001"]   # Announcement addresses
rest_service_address = "127.0.0.1:3002"       # LDK Server REST address
api_key = "your-secret-api-key"               # API key for REST requests
#pathfinding_scores_source_url = ""           # External Pathfinding Scores Source
#rgs_server_url = "https://rapidsync.lightningdevkit.org/snapshot/v2/"  # Optional: RGS URL for rapid gossip sync

# Storage settings
[storage.disk]
dir_path = "/Users/t/Library/Application Support/ldk-server/"

# Logging
[log]
level = "Debug"
file_path = "/Users/t/Library/Application Support/ldk-server/ldk-server.log"

# TLS
[tls]
#cert_path = "/path/to/tls.crt"
#key_path = "/path/to/tls.key"
hosts = ["localhost"]

# ─────────────────────────────────────────────
# CHAIN SOURCE (EXACTLY ONE)
# Regtest ⇒ bitcoind
# ─────────────────────────────────────────────

[esplora]
server_url = "https://mutinynet.com/api"  

# ─────────────────────────────────────────────
# Optional / features
# ─────────────────────────────────────────────

[rabbitmq]
connection_string = ""
exchange_name = ""

# LSPS2 Client Support
[liquidity.lsps2_client]
# The public key of the LSPS2 LSP we source just-in-time liquidity from.
node_pubkey = "<lsp node pubkey>"
# Address to connect to the LSPS2 LSP (IPv4:port, IPv6:port, OnionV3:port, or hostname:port).
address = "<lsp ip address>:9735"
# Optional token for authenticating to the LSP.
# token = ""

# Experimental LSPS2 Service Support
[liquidity.lsps2_service]
advertise_service = false

channel_opening_fee_ppm = 1000
channel_over_provisioning_ppm = 500000
min_channel_opening_fee_msat = 10000000
min_channel_lifetime = 4320
max_client_to_self_delay = 1440
min_payment_size_msat = 10000000
max_payment_size_msat = 25000000000
client_trusts_lsp = false

# require_token = ""
