name: Integration Tests

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable caching for bitcoind
        id: cache-bitcoind
        uses: actions/cache@v4
        with:
          path: bin/bitcoind-${{ runner.os }}-${{ runner.arch }}
          key: bitcoind-${{ runner.os }}-${{ runner.arch }}

      - name: Download bitcoind
        if: steps.cache-bitcoind.outputs.cache-hit != 'true'
        run: |
          source ./scripts/download_bitcoind.sh
          mkdir -p bin
          mv "$BITCOIND_EXE" bin/bitcoind-${{ runner.os }}-${{ runner.arch }}

      - name: Set bitcoind environment variable
        run: echo "BITCOIND_EXE=$( pwd )/bin/bitcoind-${{ runner.os }}-${{ runner.arch }}" >> "$GITHUB_ENV"

      - name: Run RabbitMQ integration tests
        run: cargo test --features integration-tests-events-rabbitmq --verbose --color=always -- --nocapture
        env:
          RUST_BACKTRACE: 1

      - name: Run end-to-end tests
        run: cargo test --manifest-path e2e-tests/Cargo.toml --verbose --color=always -- --test-threads=4 --nocapture
        env:
          RUST_BACKTRACE: 1
          BITCOIND_SKIP_DOWNLOAD: 1
